### ISSUE TITLE
SC: Evo Art List

### ISSUE THREAD

**Issue by Ailoso** [TeamKoprulu/SCEvoComplete#10]
### Marine
- [ ] Fire death, left leg is not animated

### Siege Tank
- [x] Dying during sieging/unsieging sequence explode visual is larger than should be
- [ ] Unload animation seems to have initial keyframes at the end position or it's not marked non looping.
- [x] Issues with Fuzzy and Tight Hit Test, selects too easily 'above' the target 
- [ ] Siege Tank selection radii are seemingly larger than a regular Siege Tank; Issue with model size exported from modelling software

### Valkyrie
- [ ] Rework Death models

### Wraith
- [ ] Rework Death models

### Command Center
- [ ] Add new Flying Animations
    - [ ] Current one has issues while moving
    - [ ] Hide the Light while flying and during construction
    - [ ] Possibly re-rig the model to add new animations
- [ ] Redo Death Model
- [x] Redo Fly Death Model
    - [ ] Add Physics Models

### Covert Ops
- [ ] Needs a new splat model

### Control Tower
- [ ] Possibly rework detach/attach animations (low priority)
- [ ] Rework Strobe light particle

### Nuclear Silo
- [ ] Rework Entire Model and animations

### Defiler
- [x] Missing Unload animation
- [ ] No target volumes
- [ ] Missing Birth animation

### Creep Colony
- [x] Adjust HitTestTight as it's too tall
- [x] Reduce amount of Ref_Damage (too many blood particles)

### Spore Colony
- [x] Basic Implementation

### Sunken Colony
- [x] Add Ground Flesh and Blood particles to existing death model
- [x] New Model Basic Implementation

### Infested CC (Low Priority)
- [ ] Needs a Zerg styled placement model
- [ ] Port new CC animations using new particles
- [ ] Create Birth Model and Animations

### Ultalisk Remastered (Low Priority)
- [ ] Normal Death model pops out instead of dissolving
- [ ] Physics death has bad physics volumes

### Shuttle
- [x] Issues with Fuzzy and Tight hit test, hard to select with dragging and targeting.
- [x] Add WarpIn animation (Birth)
- [x] Rework Thrusters to use lights, emissive and particles (possibly using the effects from the Swarm Shuttle)
- [x] No target volume

### Archons
- [x] Add orbiting particles from Coop Archon

### Citadel of Adun
- [ ] Re-center model to match where the base is at
- [ ] Model is missing Unpowered and Powered animations as well as the unpowered mesh

### Citadel of Adun
- [x] SC2 Reaver missing target volume

### Arbiter Tribunal
- [ ] Redo Arbiter Tribunal Unpowered Start and End Animations
- [ ] Redo Arbiter Tribunal Helper Refs and Volumes

**Comment by kolabearafk** [comment]
Would it be possible for SC1 buildings to look like their SC1 version instead of borrowed asset from SC2? For example, shield battery for SC1 in the Evo mod doesn't look like the shield battery from SC1, and other Zerg buildings too like evolution chamber, queen nest, etc. Thank you.
