### ISSUE TITLE
SC: Evo General Bugs

### ISSUE THREAD

**Issue by Ailoso** [TeamKoprulu/SCEvoComplete#8]
### Priority
- [x] Firebats dont gain +1 range in bunkers
- [x] Firebat weapons need to be non melee inside bunkers
- [x] Flying CC's give placement error when trying to build a Comsat, Nuclear Silo
- [x] Infesting CCs keeps already attached addons working
- [x] ~Cancelling Morphs should refund 100%~ (Implemented only for campaign mod)
- [x] ~Morphs Killed/Destroyed should refund 0%~ (Implemented only for campaign mod)

### Data To-Do
- [x] Review all building death models, a couple of them are larger or smaller than the parent
- [x] Several UI icons are missing commonly used in Observer interfaces
- [x] Do correct damage calculations for Infested Terran Suicide, Nuke and Yamato
- [ ] Workers carrying vespene should explode instead of their normal death 
- [ ] Missing water ripples: High Templar, Goliath, Vulture, Firebat, Lurker, Lurker Cocoon, Infested Terran, Archon, Dark Archon (clear terrain ripple groups when units burrow)
- [x] Hallucinations Sound Issues: Zealot, Dragoon, Marine, Overlord, Mutalisk, Queen, Probe, Firebat, SiegeTank(death model scale)
- [x] Add hallucination effects to Scarab explosion if launched from hallucinated reaver
- [x] Rename Tech Title for Core to "Broodwar Tech"
- [x] Rename Tech Categories for Extension removing the "Classic" part about them
- [x] Adjust tooltips for "sighting ranges" for Ghost, Scout and Overlords as well as the Plague tooltip
- [x] Flying buildings don't have scan attack move
- [x] Check that there are no data conflicts with all blizzard Co-op & Campaign dependencies
- [x] Add sounds to all Cocoon hatchings
- [x] Add vespene exhausted sound
- [x] Add sc1 error placement sound
- [ ] Fix Developing/Upgrading/Researching/Mutating/Evolving texts to match sc1
- [ ] Add upgrades as non abilities as passives buttons to Command cards for units
- [ ] Add support for disabling tech requirements for passives
- [x] Switch Photon cannon effects to use same as dragoon
- [x] Some placement models use sc2 buildings for their low quality model
- [x] Check if spider mines can target other spider mines
- [x] Mind controlled arbiters cant cloak after mind control
- [x] Add irradiate quirks and interactions
- [ ] In SC1, Protoss building play different 'What' sound when they are unpowered
- [ ] In SC1, Terran buildings play different 'What' sound when they are burning (see if it's possible to layer a burning sound)
- [x] Display Spore and Sunken colony defense range for when placing down Creep Colony
- [ ] Fix nuke damage to match sc1 behaviour vs structures
- [ ] Add sound entries for to replace sc2 errors sounds
- [ ] Add missile visuals for interceptor attack
- [x] Add shortened zealot help voice line to KR and english
- [x] Goliath lifted by phoenix, snap to ground on death
- [ ] Add info to spider mine what it can attack
- [ ] Add info passive button to carrier explaining interceptor behaviour
- [x] Repair button does not show on simple command card
- [x] Dark swarm covers targets on multiple cliff levels
- [ ] Mutalisk weapon bounce only if hit target (no bounce on miss)
- [x] Hatch, Lair, Hive one of them uses different worker rally button 
- [x] Scourge attack add physics impacts
- [ ] Unpowered, construction what for protoss buildings
- [ ] Check all sound match sc1

### Crossover
- [x] Do not increase max queue amount with resonant matrix
- [x] Reduce sc1 stimpack duration/make it weaker

**Questionable sc1 features**
- [x] Worker attacks should be counted as ranged instead of melee, shouldn't deal damage vs dark swarm (implemented in legacy)

**Terran**

Marine
- [ ] Marine remastered one of the fire/acid death animation variations, one of the legs is not animated (issue on blizzards model)

Comsat Station
- [x] Re-implement Scanner Sweep Radius Actor

Spider Mines
- [x] Spider Mines affected by Disruption web should have their Burrow Disabled
- [x] Spider mines don't target dark templars

**Zerg**
- [x] Starting and then canceling lair/Hive morph causes the morph animation to keep playing indefinitely or cause the animations become bugged (Hatchery looking like a Lair) (Low Priority due to possible new model)
- [ ] Drone attack should be ranged visual instead of melee

Infested Terran
- [ ] Add Infested Terran building attack toggle

Nydus Canal
- [x] If tech restrictions are disabled you cant place nydus canal exits

Infested Command Center
- [ ] Infested CC needs a new Portrait

Defiler
- [ ] Defiler no fire, acid death sounds
- [ ] Missing water ripples
- [x] Defiler Consume shouldn't be able to consume Larva

**Protoss**
- [x] Recalling units should appear where at the location of the arbiter not where it was cast.
- [x] When trying to shield battery restore something with full shield or target that is already being restored you get ‘Error’ message
- [x] Legacy mod: add instant shield restore for carrier interceptor heal
**UI**

**Comment by m0ebiuz** [comment]
> Burrowed spider mine has the structure attribute, while unburrowed it doesn’t (can’t be stasised or stormed not sure if this was possible in sc1)

I tested in the original, you can storm spider mines. (You can't stasis them, but I believe that is because it is burrowed, not because it would be a structure.)
